# src/main/resources/application.properties

# PostgreSQL ? update these for your local / cloud DB

spring.datasource.url=jdbc:postgresql://ep-plain-lake-a1jpyugg-pooler.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qTxiHov2sL8V

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Firebase Admin SDK
# Path to your service account JSON file.
# Download from: Firebase Console ? Project Settings ? Service Accounts
#                ? Generate new private key
# Put the file in src/main/resources/ and reference it like this:

firebase.service-account-path=classpath:firebase-service-account.json
#
#
## CORS ? allow the React dev server to call the backend
#
cors.allowed-origins=http://localhost:5173

# Server port
server.port=8080